import { ISheetMarker } from '../types/sheetExtras';

function isAutoGeneratedMarker(m: ISheetMarker): boolean {
  if (m.source === 'class' || m.source === 'community') return true;
  if (m.isClassSpecific) return true;
  if (m.description && m.description.length > 20) return true;
  if (m.note && m.note.length > 40) return true;
  return false;
}

/** Mantém apenas marcadores customizados simples (título + valor), sem texto de habilidades */
export function sanitizeSheetMarkers(saved: ISheetMarker[] | undefined): ISheetMarker[] {
  if (!saved?.length) return [];
  return saved
    .filter((m) => !isAutoGeneratedMarker(m))
    .map((m) => ({
      id: m.id || m.key,
      key: m.key || m.id,
      label: (m.label || 'Marcador').slice(0, 48),
      type: m.type === 'dice' || m.type === 'number' ? m.type : 'counter',
      value: typeof m.value === 'number' ? m.value : 0,
      min: m.min,
      max: m.max,
      dieSides: m.dieSides,
      source: 'custom' as const,
      isClassSpecific: false,
    }));
}

export function createCustomMarker(): ISheetMarker {
  const id = `custom_${Date.now()}`;
  return {
    id,
    key: id,
    label: 'Marcador',
    type: 'counter',
    value: 0,
    source: 'custom',
    isClassSpecific: false,
  };
}
